"use client";

import { useState } from "react";
import { Project, Dataset, Pipeline, TrainingJob, PipelineBlock } from "@/types";
import { Button } from "@/components/ui/button";
import { Download, Copy, Check, FileCode } from "lucide-react";
import { BLOCK_DEFINITIONS } from "@/components/step2/blockDefinitions";

interface Step5ClientProps {
  project: Project;
  dataset: Dataset | null;
  pipeline: Pipeline | null;
  job: TrainingJob | null;
}

function generateArchitecturePy(
  project: Project,
  dataset: Dataset | null,
  pipeline: Pipeline | null,
  job: TrainingJob | null
): string {
  const datasetFile = dataset?.file_name ?? "your_dataset.csv";
  const targetCol = dataset?.target_column ?? "target";
  const modelType = job?.model_type ?? "random_forest";
  const hyperparams = (job?.hyperparameters as Record<string, unknown>) ?? {};
  const blocks: PipelineBlock[] = pipeline?.config ?? [];
  const problemType = project.problem_type ?? "classification";

  const modelClass: Record<string, string> = {
    random_forest: `RandomForestClassifier` + (problemType === "regression" ? ".replace('Classifier','Regressor')" : ""),
    gradient_boosting: `GradientBoostingClassifier`,
    decision_tree: `DecisionTreeClassifier`,
    logistic_regression: `LogisticRegression`,
    svm: `SVC`,
    knn: `KNeighborsClassifier`,
    linear_regression: `LinearRegression`,
    ridge: `Ridge`,
    lasso: `Lasso`,
  };

  const importMap: Record<string, string> = {
    random_forest: "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor",
    gradient_boosting: "from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor",
    decision_tree: "from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor",
    logistic_regression: "from sklearn.linear_model import LogisticRegression",
    svm: "from sklearn.svm import SVC, SVR",
    knn: "from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor",
    linear_regression: "from sklearn.linear_model import LinearRegression",
    ridge: "from sklearn.linear_model import Ridge",
    lasso: "from sklearn.linear_model import Lasso",
  };

  const pipelineSteps = blocks.map((block) => {
    const def = BLOCK_DEFINITIONS[block.block_type];
    const cols = block.column_targets.length > 0 ? block.column_targets : ["*"];
    return `    # ${def.label} — applies to: ${cols.slice(0,3).join(", ")}${cols.length > 3 ? "..." : ""}
    # block_type: ${block.block_type}, params: ${JSON.stringify(block.params)}`;
  }).join("\n");

  const hyperStr = Object.entries(hyperparams)
    .filter(([k]) => !["model_type","train_val_split","random_seed","stratified_split","layers","optimizer","learning_rate","epochs","batch_size","early_stopping","early_stopping_patience"].includes(k))
    .map(([k, v]) => `    ${k}=${typeof v === "string" ? `"${v}"` : v}`)
    .join(",\n");

  return `# =============================================================================
# architecture.py — Generated by Zeal Modelling
# Project: ${project.name}
# Model type: ${project.model_type} / ${problemType}
# Generated: ${new Date().toISOString()}
# =============================================================================

# =============================================================================
# 1. IMPORTS
# =============================================================================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
${importMap[modelType] ?? "from sklearn.ensemble import RandomForestClassifier"}
from sklearn.metrics import ${problemType === "classification" ? "accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix" : "mean_absolute_error, mean_squared_error, r2_score"}
import joblib

# =============================================================================
# 2. DATA LOADING
# =============================================================================
# Load your dataset — ensure column names match exactly
df = pd.read_csv("${datasetFile}")

# Features and target
X = df.drop(columns=["${targetCol}"])
y = df["${targetCol}"]

print(f"Dataset shape: {df.shape}")
print(f"Target column: '${targetCol}'")

# =============================================================================
# 3. FEATURE ENGINEERING PIPELINE
# =============================================================================
# Pipeline config from Zeal Modelling (${blocks.length} blocks)
${blocks.length === 0 ? "# No transformation blocks defined — raw features used" : pipelineSteps}

# Identify column groups
numeric_features = X.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = X.select_dtypes(include=["object", "category"]).columns.tolist()

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler()),
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="constant", fill_value="missing")),
    ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore")),
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ],
    remainder="drop"
)

# =============================================================================
# 4. MODEL DEFINITION
# =============================================================================
# ${modelClass[modelType] ?? "RandomForestClassifier"} with hyperparameters from Zeal config
model_params = {
${hyperStr || "    # Default parameters"}
}

from sklearn.ensemble import ${problemType === "classification" ? "RandomForestClassifier" : "RandomForestRegressor"} as ModelClass

full_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", ModelClass(**model_params)),
])

# =============================================================================
# 5. TRAINING
# =============================================================================
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=${(1 - (job?.train_val_split ?? 0.8)).toFixed(2)},
    random_state=${(job?.random_seed ?? 42)},
    ${problemType === "classification" ? "stratify=y,  # Stratified split for classification" : "# Regression: no stratification"}
)

print(f"Training samples: {len(X_train)}, Validation samples: {len(X_val)}")

full_pipeline.fit(X_train, y_train)
print("\\nTraining complete.")

# =============================================================================
# 6. EVALUATION
# =============================================================================
y_pred = full_pipeline.predict(X_val)

${problemType === "classification" ? `print("\\n=== Classification Results ===")
print(f"Accuracy:  {accuracy_score(y_val, y_pred):.4f}")
print(f"F1 Score:  {f1_score(y_val, y_pred, average='weighted'):.4f}")
print(f"Precision: {precision_score(y_val, y_pred, average='weighted'):.4f}")
print(f"Recall:    {recall_score(y_val, y_pred, average='weighted'):.4f}")
print("\\nClassification Report:")
print(classification_report(y_val, y_pred))
print("\\nConfusion Matrix:")
print(confusion_matrix(y_val, y_pred))` : `print("\\n=== Regression Results ===")
mse = mean_squared_error(y_val, y_pred)
print(f"MAE:  {mean_absolute_error(y_val, y_pred):.4f}")
print(f"RMSE: {np.sqrt(mse):.4f}")
print(f"R²:   {r2_score(y_val, y_pred):.4f}")`}

# =============================================================================
# 7. MODEL SERIALISATION
# =============================================================================
joblib.dump(full_pipeline, "model.pkl")
print("\\nModel saved to model.pkl")
print("Load with: pipeline = joblib.load('model.pkl')")
`;
}

function generateRequirementsTxt(project: Project): string {
  return `# requirements.txt — Generated by Zeal Modelling
# Project: ${project.name}

scikit-learn>=1.4.0
pandas>=2.0.0
numpy>=1.26.0
joblib>=1.3.0
${project.model_type === "deep_learning" ? "torch>=2.0.0\ntorchvision>=0.15.0\n" : ""}matplotlib>=3.8.0
seaborn>=0.13.0
`;
}

export default function Step5Client({ project, dataset, pipeline, job }: Step5ClientProps) {
  const [copied, setCopied] = useState(false);

  const architectureCode = generateArchitecturePy(project, dataset, pipeline, job);
  const requirementsTxt = generateRequirementsTxt(project);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(architectureCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (content: string, filename: string) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadAll = () => {
    // Download architecture.py
    handleDownload(architectureCode, "architecture.py");
    // Download requirements.txt with a slight delay
    setTimeout(() => handleDownload(requirementsTxt, "requirements.txt"), 300);
  };

  return (
    <div className="max-w-5xl mx-auto px-6 py-8">
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-1">
          <span className="inline-flex items-center justify-center w-6 h-6 rounded-full bg-[#1B3A5C] text-white text-xs font-bold">5</span>
          <h2 className="text-lg font-semibold text-[#1A1A1A]">Export</h2>
        </div>
        <p className="text-sm text-[#666666]">
          Download production-ready Python code that reproduces your trained model.
        </p>
      </div>

      {/* Export actions */}
      <div className="flex flex-wrap gap-3 mb-6">
        <Button onClick={handleDownloadAll} size="lg">
          <Download className="w-4 h-4" />
          Download ZIP (all files)
        </Button>
        <Button variant="outline" onClick={() => handleDownload(architectureCode, "architecture.py")}>
          <FileCode className="w-4 h-4" />
          architecture.py
        </Button>
        <Button variant="outline" onClick={() => handleDownload(requirementsTxt, "requirements.txt")}>
          <FileCode className="w-4 h-4" />
          requirements.txt
        </Button>
      </div>

      {/* Code preview */}
      <div className="bg-white rounded-lg border border-[#CCCCCC] shadow-sm overflow-hidden mb-6">
        <div className="flex items-center justify-between px-4 py-3 bg-[#1B3A5C]">
          <div className="flex items-center gap-2">
            <FileCode className="w-4 h-4 text-white/70" />
            <span className="text-sm font-medium text-white">architecture.py</span>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleCopy}
            className="text-white/70 hover:text-white hover:bg-white/10"
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : "Copy"}
          </Button>
        </div>
        <div className="overflow-auto max-h-[60vh]">
          <pre className="p-5 text-sm text-[#1A1A1A] font-mono leading-relaxed bg-[#F8F9FA] overflow-x-auto">
            <code>{architectureCode}</code>
          </pre>
        </div>
      </div>

      {/* Requirements */}
      <div className="bg-white rounded-lg border border-[#CCCCCC] shadow-sm overflow-hidden">
        <div className="flex items-center justify-between px-4 py-3 bg-[#F8F9FA] border-b border-[#CCCCCC]">
          <span className="text-sm font-medium text-[#1A1A1A]">requirements.txt</span>
        </div>
        <pre className="p-4 text-sm text-[#1A1A1A] font-mono leading-relaxed">
          <code>{requirementsTxt}</code>
        </pre>
      </div>

      {/* Usage instructions */}
      <div className="mt-6 p-4 bg-[#D6E4F0] border border-[#2E75B6]/20 rounded-lg">
        <h4 className="font-semibold text-[#1B3A5C] mb-2 text-sm">How to run</h4>
        <pre className="text-xs font-mono text-[#1B3A5C] space-y-1">
{`pip install -r requirements.txt
python architecture.py`}
        </pre>
      </div>
    </div>
  );
}
